# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GmlyDmBKPJSFHajKHgBhI2alJsGaU2Ml
"""

import pytest
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

def test_linear_regression():
    # Przykładowe dane do testu
    X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
    Y = np.array([3, 7, 11, 15])

    # Skalowanie
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # Model
    model = LinearRegression()
    model.fit(X_scaled, Y)
    predictions = model.predict(X_scaled)

    # Test: Sprawdzamy, czy R^2 jest większe od 0
    assert r2_score(Y, predictions) > 0

def test_random_forest():
    # Przykładowe dane do testu
    X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
    Y = np.array([3, 7, 11, 15])

    # Skalowanie
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # Model
    model = RandomForestRegressor(n_estimators=100)
    model.fit(X_scaled, Y)
    predictions = model.predict(X_scaled)

    # Test: Sprawdzamy, czy R^2 jest większe od 0
    assert r2_score(Y, predictions) > 0