name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: List files in the tests directory
      run: |
        ls -R tests  # Sprawdzamy zawartość folderu 'tests'

    - name: Run tests with pytest
      run: |
        pytest tests/test.py --maxfail=1 --disable-warnings -q  # Określamy dokładny plik testowy
