name: Run Tests

on:
  push:
    branches:
      - main  # Uruchamia testy przy pushu na główną gałąź
  pull_request:
    branches:
      - main  # Uruchamia testy przy pull requestach na główną gałąź

jobs:
  test:
    runs-on: ubuntu-latest  # Używamy najnowszej wersji Ubuntu dla środowiska testowego

    steps:
    # Kroki do wykonania w ramach zadania
    - name: Checkout code
      uses: actions/checkout@v3  # Klonuje Twoje repozytorium

    - name: Set up Python
      uses: actions/setup-python@v3  # Konfiguruje środowisko Python
      with:
        python-version: 3.10  # Wersja Pythona, którą chcesz używać

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Aktualizuje pip
        pip install -r requirements.txt  # Instalacja zależności z pliku requirements.txt

    - name: List files in tests folder  # Debugowanie: wypisuje pliki w folderze testów
      run: ls -R tests/

    - name: Run tests
      run: |
        pytest tests --maxfail=1 --disable-warnings -q  # Uruchamia pytest w folderze tests
