name: CI Pipeline

on:
  push:
    branches:
      - main  # lub inna gałąź

jobs:
  build:
    runs-on: ubuntu-latest  # Lub odpowiedni system operacyjny

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Użyj wersji Pythona, która jest bardziej kompatybilna

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas==2.1.3
        pip install -r requirements.txt
