name: Insurance Cost Prediction CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out repository
    - name: Check out repository
      uses: actions/checkout@v2

    # 2. Set up Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --no-require-hashes

    # 4. Copy test.py to the correct location
    - name: Copy test.py
      run: cp /content/drive/MyDrive/Colab\ Notebooks/COST\ insurence/test.py tests/

    # 5. Download insurance CSV from Google Drive
    - name: Download insurance CSV
      run: |
        if [ -f "/content/drive/MyDrive/Colab\ Notebooks/COST\ insurence/insurance.csv" ]; then
          cp /content/drive/MyDrive/Colab\ Notebooks/COST\ insurence/insurance.csv data/
        else
          curl -L -o data/insurance.csv https://drive.google.com/uc?export=download&id=1-9hXY8s5kDU4JEmQiehvLV_h8nc3MYy2
        fi

    # 6. Run tests with pytest
    - name: Run tests with pytest
      run: |
        pytest tests/ --junitxml=test-results.xml
      continue-on-error: false

    # 7. Upload test results as artifacts
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results.xml

  generate-charts:
    needs: test
    runs-on: ubuntu-latest

    steps:
    # 1. Check out repository
    - name: Check out repository
      uses: actions/checkout@v2

    # 2. Set up Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --no-require-hashes

    # 4. Download insurance CSV from Google Drive
    - name: Download insurance CSV
      run: |
        if [ -f "/content/drive/MyDrive/Colab\ Notebooks/COST\ insurence/insurance.csv" ]; then
          cp /content/drive/MyDrive/Colab\ Notebooks/COST\ insurence/insurance.csv data/
        else
          curl -L -o data/insurance.csv https://drive.google.com/uc?export=download&id=1-9hXY8s5kDU4JEmQiehvLV_h8nc3MYy2
        fi

    # 5. Run script to generate charts
    - name: Run script to generate charts
      run: |
        python /content/drive/MyDrive/Colab\ Notebooks/COST\ insurence/Cost_insurence_Vol2.py

    # 6. Save charts as artifacts
    - name: Upload charts
      uses: actions/upload-artifact@v3
      with:
        name: charts
        path: "*.png"
