name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Install build tools (optional)
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Run tests or scripts
      run: |
        # Jeśli masz testy:
        # pytest
        # Jeśli uruchamiasz główny skrypt:
        python main.py
